make maple-mini
make maple-rev3
make maple-rev5
make generic-pc13
make generic-pg15
make generic-pd2
make generic-pd1
make generic-pa1
make generic-pa1-button-pa8
make generic-pb9
make generic-pe2
make generic-pa9
make generic-pe5
make generic-pe5-button-pa0
make generic-pb7
make generic-pb0
make stbee
make naze32
make generic-pb12
make hytiny-stm32f103t
make dso138
make gd32f1-generic-pc13
make gd32f1-frankenmaple
