make maple-mini
make clean
make maple-rev3
make clean
make maple-rev5
make clean
make generic-pc13
make clean
make generic-pg15
make clean
make generic-pd2
make clean
make generic-pd1
make clean
make generic-pa1
make clean
make generic-pb9
make clean
make generic-pe2
make clean
make generic-pa9
make clean
make generic-pe5
make clean
make generic-pe5-button-pa0
make clean
make generic-pb7
make clean
make generic-pb0
make clean
make stbee
make clean
make naze32